#!/usr/bin/env python
# -*- encoding: utf-8 -*-

text.usetex         : False
mathtext.fontset    : stixsans
text.color          : white  
xtick.color         : white  
ytick.color         : white  
axes.labelcolor     : white  
axes.edgecolor      : white  
axes.facecolor      : black  
patch.edgecolor     : white
savefig.edgecolor   : black
savefig.facecolor   : black
axes.color_cycle    : red, green, blue, cyan, magenta, yellow, chartreuse, lightblue, lightgreen, orange
